### ISSUE TITLE
Error on Compiling.

### ISSUE THREAD

**Issue by nonunknown** [rdbo/Memory#1]
Hey Man finally I found a X-Platform Memory management this is awesome, but when i execute the command
`./Compile.sh` I got this message:

![Screenshot from 2020-07-03 09-07-01](https://user-images.githubusercontent.com/58845030/86467853-95e08d00-bd0c-11ea-903d-5583779dcb66.png)

**update**

Solved the problem using: `sudo apt-get install gcc-multilib g++-multilib`

**update 2**

_solved_
`Since compile works fine now, the generated file "mem.o" is generated but it dissapper, tried compiling from terminal and vscode and using sudo too. any idea?`

Seems that compile.sh file has a line `rm mem.o` but why does you decided to remove mem.?

**Comment by rdbo** [comment]
"mem.o" is the object file used during the compilation of "mem.a".
It is removed because, once "mem.a" is there, "mem.o" is just an old object file that is not needed anymore.
