### ISSUE TITLE
Error When running Any Method!

### ISSUE THREAD

**Issue by nonunknown** [rdbo/Memory#2]
Based on this approach:

![Screenshot from 2020-07-04 18-17-09](https://user-images.githubusercontent.com/58845030/86521101-b3077f80-be22-11ea-98df-906511d69026.png)

The result:

![Screenshot from 2020-07-04 18-16-54](https://user-images.githubusercontent.com/58845030/86521102-bdc21480-be22-11ea-9ae9-8a37e894ce37.png)

**Comment by rdbo** [comment]
You forgot to compile mem.cpp (or mem.a, in case you're using the static library). Run the following:
g++ \<parameters\> src/main.cpp src/mem.cpp -o bin/main
Also, I recommend you use the code of the "backup" branch. It is more stable and is currently made for Linux specifically. Tested on Debian 10.

**Comment by nonunknown** [comment]
Thanks for the answer I'll try here
